# NumPy

In [35]:
# conda install numpy
# pip install numpy
# !pip install numpy
""" yorum satırı """

' yorum satırı '

## Importing Numpy

In [5]:
import numpy as np

## Creating NumPy Arrays from Objects

### From a Python List

In [58]:
my_list = [1,2,3,4,5]

In [66]:
my_list = [1,2,3,4,5]
# print(my_list)
my_list

[1, 2, 3, 4, 5]

In [50]:
type(my_list)

list

In [60]:
array1=np.array([1,2,3,4,5])
array1

array([1, 2, 3, 4, 5])

In [68]:
my_array = np.array(my_list)
print(my_array)

[1 2 3 4 5]


In [70]:
type(my_array)

numpy.ndarray

In [72]:
my_matris=[[1,2], [3,4], [5,6]]
my_matris

[[1, 2], [3, 4], [5, 6]]

In [74]:
type(my_matris)

list

In [76]:
len(my_matris)

3

In [80]:
print(np.array(my_matris))

[[1 2]
 [3 4]
 [5 6]]


## Built-in Methods to create arrays

### arange

In [96]:
print(list(range(0, 10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [98]:
print(*range(0, 10))

0 1 2 3 4 5 6 7 8 9


In [100]:
print(list(range(5, 10)))

[5, 6, 7, 8, 9]


In [102]:
print(list(range(5, 100, 5)))

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]


In [104]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
print(np.arange(2,10, 2))

[2 4 6 8]


### zeros and ones

Sıfır ve bir dizileri döndürür

In [112]:
print(np.zeros(3))

[0. 0. 0.]


In [118]:
print(np.zeros((5,2), dtype=int))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [122]:
print(np.zeros((5,2), dtype=bool))

[[False False]
 [False False]
 [False False]
 [False False]
 [False False]]


In [124]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [126]:
np.ones((5,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [128]:
np.ones((5,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [138]:
np.ones((5,3), str)

array([['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

### linspace
Belirli aralıkta eşit aralıklı sayılar döndürür

In [140]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [142]:
np.linspace(0,10, 3)

array([ 0.,  5., 10.])

In [144]:
np.linspace(0,10, 3, dtype=int)

array([ 0,  5, 10])

In [150]:
np.linspace(0,5, 20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [148]:
np.linspace(0,5, 20, dtype=int)

array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 5])

### eye
Birim matrisi oluşturur

In [152]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [156]:
np.eye(9, k=3)

array([[0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [158]:
np.eye(9, k=3, dtype=int)

array([[0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

## Random
### rand
[0,1) üzerinden tekdüze bir dağılımından rastgele örnekler döndürür

In [166]:
np.random.rand(2)

array([0.90930556, 0.44928828])

### randn

"Standard normal" dağılımdan bir örnek (örnekler) döndürür. 
Standart normal dağılım, ortalaması 0 ve standart sapması 1 olan bir normal dağılımdır.

In [176]:
np.random.randn(3)

array([ 0.77637098,  0.20233733, -1.51819009])

### randint

randint fonksiyonu, belirli bir aralıkta rastgele tamsayılar üretmek için kullanılır.

In [226]:
np.random.randint(2,10,5)

array([6, 4, 7, 5, 8])

### seed

In [228]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [232]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

## Array Attributes and Methods

In [7]:
arr = np.arange(25)
arr2= np.random.randint(0,50,10)

In [236]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [238]:
arr2

array([47,  9, 13, 40,  4, 40, 28,  0, 46,  5])

### reshape

In [13]:
arr.shape

(25,)

In [258]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [11]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [264]:
arr = arr.reshape(5,5)

In [268]:
arr.shape

(5, 5)

In [272]:
arr.reshape(-1) #Çok boyutlu array leri 1 boyuta döndürür

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [274]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min, argmax, argmin

In [276]:
arr2

array([47,  9, 13, 40,  4, 40, 28,  0, 46,  5])

In [278]:
arr2.max()

47

In [280]:
arr2.min()

0

In [282]:
arr2.argmax() #maksimum sayının indeksini döndürür

0

In [284]:
arr2.argmin() #minimum sayının indeksini döndürür

7

### shape

In [286]:
arr2.shape

(10,)

### dtype

In [288]:
arr.dtype

dtype('int32')

## NumPy Indexing and Selection

Bir dizinin belirli bir bölümünü seçmek veya alt diziler oluşturulması işlemlerine dilimleme (slicing) denir. Bunun için indeksler kullanılır.

In [290]:
arr = np.arange(8,18)
arr

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [296]:
arr[1]

9

In [298]:
arr[0:5] #slicing

array([ 8,  9, 10, 11, 12])

In [300]:
arr[:5]

array([ 8,  9, 10, 11, 12])

In [302]:
arr[6:]

array([14, 15, 16, 17])

In [304]:
arr[6:8]

array([14, 15])

### Broadcasting

In [306]:
arr

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [310]:
arr[5] = 100
arr

array([  8,   9,  10,  11,  12, 100,  14,  15,  16,  17])

In [312]:
arr[:5] = 101
arr

array([101, 101, 101, 101, 101, 100,  14,  15,  16,  17])

In [314]:
arr[:] = 101
arr

array([101, 101, 101, 101, 101, 101, 101, 101, 101, 101])

In [316]:
arr=np.arange(11)

In [318]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [320]:
arr_slicing = arr[:6]
arr_slicing 

array([0, 1, 2, 3, 4, 5])

In [322]:
arr_slicing[:]=90
arr_slicing

array([90, 90, 90, 90, 90, 90])

In [324]:
arr

array([90, 90, 90, 90, 90, 90,  6,  7,  8,  9, 10])

In [326]:
#Array lerde doğrudan atamak yapmak yerine copy() kullanmak daha etkilidir. Çünkü atanan değişkende yapılan değişiklik kaynak değişkeni de etkiler.
arr_copy = arr.copy()
arr_copy

array([90, 90, 90, 90, 90, 90,  6,  7,  8,  9, 10])

## Indexing 2D array (matrices)

In [15]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [17]:
arr_2d.shape

(3, 3)

In [27]:
arr_2d[1]

array([20, 25, 30])

In [21]:
arr_2d[2]

array([35, 40, 45])

In [23]:
arr_2d[1][1]

25

In [29]:
arr_2d[1, 1]

25

In [31]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [33]:
arr_2d[:2,1]

array([10, 25])

In [41]:
arr_2d[1:, :]

array([[20, 25, 30],
       [35, 40, 45]])

## Conditional Selection

In [43]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [47]:
liste = [4,5,6,7]
liste > 4

TypeError: '>' not supported between instances of 'list' and 'int'

In [49]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [53]:
arr[arr<=3]

array([1, 2, 3])

In [57]:
arr==5

array([False, False, False, False,  True, False, False, False, False,
       False])

In [55]:
arr[arr==5]

array([5])

In [59]:
arr[arr!=5]

array([ 1,  2,  3,  4,  6,  7,  8,  9, 10])

## Aritmetic Operations

In [61]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
liste

[4, 5, 6, 7]

In [69]:
liste + liste

[4, 5, 6, 7, 4, 5, 6, 7]

In [89]:
liste + 11

TypeError: can only concatenate list (not "int") to list

In [71]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [73]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [79]:
arr / arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [77]:
arr // arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [81]:
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [87]:
arr2 = np.arange(0,11)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
arr2 / arr2

C:\Users\oznur\AppData\Local\Temp\ipykernel_17264\3053098687.py:1: RuntimeWarning: invalid value encountered in divide
  arr2 / arr2


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [93]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
arr + 11

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [97]:
arr - 2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [99]:
arr * 3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

## Universal Functions

In [101]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [107]:
np.sqrt(arr) #karekökünü alır

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [109]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [111]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [113]:
np.std(arr)

2.8722813232690143

## Summary Statistics on Arrays

In [115]:
len(arr)

10

In [117]:
arr.sum()

55

In [119]:
arr.mean()

5.5

In [121]:
arr.max()

10

In [123]:
arr.min()

1

## Axis Logic

In [125]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [127]:
arr_2d.sum()

225

In [129]:
arr_2d.sum(axis=0)

array([60, 75, 90])

In [131]:
arr_2d.sum(axis=1)

array([ 30,  75, 120])

In [133]:
arr_2d.mean(axis=0)

array([20., 25., 30.])

In [137]:
arr_2d.mean(axis=1, dtype=int)

array([10, 25, 40])

## Useful Functions

In [139]:
arr = np.array([1, 5, 8, 6, 4, 8 ,9 , 1, 0])
arr

array([1, 5, 8, 6, 4, 8, 9, 1, 0])

### where

In [141]:
np.where(arr%2==0)  #koşulu sağlayan değerlerin indeklerini döndürür

(array([2, 3, 4, 5, 8], dtype=int64),)

In [143]:
np.where(arr%2==1)

(array([0, 1, 6, 7], dtype=int64),)

In [145]:
arr[np.where(arr%2==1)]

array([1, 5, 9, 1])

In [147]:
arr[arr%2==1]

array([1, 5, 9, 1])

### sort

In [149]:
arr

array([1, 5, 8, 6, 4, 8, 9, 1, 0])

In [151]:
np.sort(arr)

array([0, 1, 1, 4, 5, 6, 8, 8, 9])

In [223]:
arr2.reshape(-1).sort()
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [5, 7, 9]])

In [231]:
arr2.reshape(-1).sort()

In [233]:
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [5, 7, 9]])

In [225]:
arr2 = np.array([[1,2,5], [9,3,7], [5,4,0]])
arr2

array([[1, 2, 5],
       [9, 3, 7],
       [5, 4, 0]])

In [229]:
np.sort(arr2)

array([[1, 2, 5],
       [3, 7, 9],
       [0, 4, 5]])

In [157]:
np.sort(arr2, axis=0)

array([[1, 2, 0],
       [5, 3, 5],
       [9, 4, 7]])

In [159]:
np.sort(arr2, axis=1)

array([[1, 2, 5],
       [3, 7, 9],
       [0, 4, 5]])

### concatenate

In [167]:
arr

array([1, 5, 8, 6, 4, 8, 9, 1, 0])

In [169]:
arr+arr

array([ 2, 10, 16, 12,  8, 16, 18,  2,  0])

In [171]:
arr=np.array([1,2,3])
arr2 = np.array([4,5,6])

In [179]:
arr
arr2

array([4, 5, 6])

In [181]:
display(arr,arr2)

array([1, 2, 3])

array([4, 5, 6])

In [185]:
np.concatenate((arr, arr2), dtype=float)

array([1., 2., 3., 4., 5., 6.])

In [187]:
arr3 = np.array([[1,2,5], [9,3,7], [5,4,0]])
arr3

array([[1, 2, 5],
       [9, 3, 7],
       [5, 4, 0]])

In [199]:
np.concatenate((arr3, arr3))

array([[1, 2, 5],
       [9, 3, 7],
       [5, 4, 0],
       [1, 2, 5],
       [9, 3, 7],
       [5, 4, 0]])

In [193]:
np.concatenate((arr3, arr3, arr3), axis=1)

array([[1, 2, 5, 1, 2, 5, 1, 2, 5],
       [9, 3, 7, 9, 3, 7, 9, 3, 7],
       [5, 4, 0, 5, 4, 0, 5, 4, 0]])

### stack

In [201]:
display(arr, arr2)

array([1, 2, 3])

array([4, 5, 6])

In [207]:
np.stack((arr, arr2))

array([[1, 2, 3],
       [4, 5, 6]])

In [209]:
np.stack((arr, arr2), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [211]:
np.hstack((arr, arr2))

array([1, 2, 3, 4, 5, 6])

In [213]:
np.vstack((arr, arr2))

array([[1, 2, 3],
       [4, 5, 6]])

### array_split

In [235]:
arr = np.arange(1,7)
arr

array([1, 2, 3, 4, 5, 6])

In [239]:
np.array_split(arr, 3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [245]:
arr2=np.arange(0,10)

In [247]:
np.array_split(arr2, 4)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7]), array([8, 9])]

In [251]:
np.array_split(arr2, [3,5,7])

[array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8, 9])]

### unique

In [253]:
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])
arr

array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

In [255]:
np.unique(arr)

array([1, 2, 3, 4, 5, 6, 7])

### union1d

In [257]:
arr1= np.array([1,2,3,4])
arr2=np.array([3,4,5,6])

In [259]:
np.union1d(arr1, arr2)

array([1, 2, 3, 4, 5, 6])

### intersect1d

In [261]:
arr1= np.array([1,2,3,4])
arr2=np.array([3,4,5,6])

In [263]:
np.intersect1d(arr1, arr2)

array([3, 4])